# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Questify' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Questify
pod 'Socket.IO-Client-Swift', '~> 14.0.0'
pod 'SwiftyJSON', '~> 4.0' #should be downgraded also

#pod 'Alamofire', '~> 4.7'  #should be downgraded for iOS 9.*/SW 4.0 compatibility

end
